name: Sync to GitLab

on:
  schedule:
    - cron: '0 12 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run update script
      run: |
        echo "Running update script..."
        python get_version.py  # 运行更新脚本

    - name: Set up GitLab credentials
      run: |
        git config --global user.name "Sczr0"
        git config --global user.email "sczr0710@163.com"
        git config --global credential.helper store
        echo "https://${{ secrets.GITLAB_TOKEN }}:x-oauth-basic@gitlab.com" > ~/.git-credentials

    - name: Add GitLab remote
      run: git remote add gitlab https://gitlab.com/Sczr0/phigros-upd.git

    - name: Fetch from GitLab
      run: git fetch gitlab

    - name: Merge changes
      run: git merge origin/main || echo "No changes to merge"

    - name: Push to GitLab
      run: |
        git push gitlab main
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

    - name: Commit and push version info
      run: |
        git add version_info.json
        git commit -m "Update version info"
        git push gitlab main
