name: Sync to GitLab

on:
  push:
    branches:
      - main  # 触发同步的分支
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: |
          git remote add gitlab https://gitlab.com/Sczr0/phigros-upd.git
          git config --global credential.helper store
          echo "https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com" > ~/.git-credentials
          git push --mirror gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
