name: Auto Update and Sync to GitLab

on:
  schedule:
    - cron: '0 11 * * *'  # 每天中午12点运行
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  workflow_dispatch:  # 手动触发支持

jobs:
  update_and_sync:
    runs-on: ubuntu-latest

    # 设置权限，允许对仓库内容进行写操作
    permissions:
      contents: write

    steps:
    # Step 1: 检出代码
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 获取完整历史记录，确保后续操作无问题

    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    # Step 4: 运行更新脚本
    - name: Run update script
      run: |
        echo "Running update script..."
        python get_version.py  # 运行您的更新脚本

    # Step 5: 提交更改
    - name: Commit changes
      run: |
        echo "Committing changes..."
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add version_info.json
        git commit -m "Update version info"
        git push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 6: 推送更改到 GitHub
    - name: Push changes to GitHub
      run: |
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push origin main

    # Step 7: 设置 SSH 密钥（用于 GitLab）
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    # Step 8: 添加 GitLab 远程仓库
    - name: Add GitLab remote
      run: git remote add gitlab git@gitlab.com:Sczr0/phigros-upd.git

    # Step 9: 从 GitLab 获取内容
    - name: Fetch from GitLab
      run: git fetch gitlab

    # Step 10: 合并内容
    - name: Merge changes
      run: git merge origin/main || echo "No changes to merge"

    # Step 11: 强制推送到 GitLab
    - name: Push to GitLab
      run: git push --force gitlab main
