name: Mirror to GitLab

on:
  push:
    branches:
      - main  # 监视主分支的推送
  schedule:
    - cron: '0 12 * * *'  # 每天午夜运行（根据需要调整）

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 获取完整历史

    - name: Set up GitLab credentials
      run: |
        git config --global user.name "Sczr0"
        git config --global user.email "sczr0710@163.com"
        echo "https://${{ secrets.GITLAB_TOKEN }}:x-oauth-basic@gitlab.com" > ~/.git-credentials

    - name: Add GitLab remote
      run: git remote add gitlab https://gitlab.com/Sczr0/phigros-upd.git

    - name: Push to GitLab
      run: |
        git fetch gitlab
        git push --mirror gitlab  # 使用镜像推送到 GitLab
