name: Auto Update Phigros Info

on:
  schedule:
    - cron: '0 12 * * *'  # 每天中午运行
  workflow_dispatch:     # 手动触发支持

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码库
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    # 4. 运行 Python 脚本，生成 JSON 文件
    - name: Run update script
      run: |
        python get_version.py

    # 5. 配置 Git 用户信息
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # 6. 提交并推送更改
    - name: Commit and push changes
      run: |
        git add version_info.json
        git commit -m "Update version_info.json [skip ci]" || echo "No changes to commit"
        git push origin HEAD
